"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const todos_controllers_1 = require("../controllers/todos-controllers");
const router = (0, express_1.Router)();
router.get('/', todos_controllers_1.getToDo);
router.post('/todo', todos_controllers_1.postToDo);
router.patch('/todo/:todoId', todos_controllers_1.patchToDo);
router.delete('/todo/:todoId', todos_controllers_1.deleteToDo);
exports.default = router;
